services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: inventar-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=inventar
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - mysql
    networks:
      - inventar-network

  mysql:
    image: mysql:8.0
    container_name: inventar-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inventar
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: inventar
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inventar-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: inventar-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - inventar-network

volumes:
  mysql_data:
    driver: local

networks:
  inventar-network:
    driver: bridge
